### ISSUE TITLE
Different experimental results between conference paper and journal paper

### ISSUE THREAD

**Issue by gpengzhi** [uvavision/visual-pivoting#1]
Congratulations on the interesting work!

Why is there a mismatch between tables 1 and 2 in "Backpropagation-Based Decoding for Multimodal Machine Translation" and tables 1 and 2 in "Using Visual Feature Space as a Pivot Across Languages"?

How is the BLEU score computed given the fact that there is no parallel sentences in Multi30K task 2? Did you use five corresponding image descriptions as multiple references?

Did you use BPE in tables 1 and 2?

**Comment by ziyanyang** [comment]
Sorry for the late reply. The results in "Backpropagation-Based ..." are obtained by jointly training three languages, and table 1 reports the results for German and English. But the results in "Using Visual Feature Space ..." are obtained by only training on German and English data. 

For Multi30K task 2, yes, each image has 5 references. No BPE for tables 1 and 2.
